### PR TITLE
feat: add silent option

### PR DESCRIPTION
**Pull request by ryoppippi**
### Description

add `silent` option just like `tsup` has

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Made some tweaks via https://github.com/sxzz/tsdown/commit/4c9312bd7d39a38489a50f179a107c58da88180c

**Comment by ryoppippi** [comment]
@sxzz I'm developing a new library, and inside the library calls `build` function from `tsdown`, like this:
```ts
import { build } from '@sxzz/tsdown';
```

How can I silent the log in this case?

**Comment by sxzz** [comment]
I exported `logger` for this case
https://github.com/sxzz/tsdown/commit/56efd13c29a678315967bd9aecc94486e6624e6b

**Comment by ryoppippi** [comment]
Oh, Thanks! |'ll use that

**Pull request merged**
